---
engines:
  eslint:
    exclude_paths:
      - "docs/enterprise/js/package-catalog.js"
  opengrep:
    exclude_paths:
      - "docs/enterprise/js/package-catalog.js"
  semgrep:
    exclude_paths:
      - "docs/enterprise/js/package-catalog.js"
